apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poplingo-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.30
    helm:
      releaseName: poplingo-postgres
      values: |
        auth:
          username: app
          password: app
          database: poplingo
        primary:
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          persistence:
            enabled: true
            size: 2Gi
