apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poplingo-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.6.4
    helm:
      releaseName: poplingo-redis
      values: |
        architecture: standalone
        auth:
          enabled: false
        master:
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          persistence:
            enabled: true
            size: 1Gi
